[Template merge - und] Massive template merge to bring the startup languages in line with the other languages and the und/ template.
git-svn-id: https://gtsvn.uit.no/langtech/trunk/startup-langs/bla@94929 c7155fb1-f0a7-4240-a2fc-2600b6f42f90

diff --git a/test/run-morph-tester.sh.in b/test/run-morph-tester.sh.in
--- a/test/run-morph-tester.sh.in
+++ b/test/run-morph-tester.sh.in
@@ -88,24 +88,41 @@ else
 fi
 
 function run_tests() {
+# --output final/terse/compact/normal - OR:
+# --silent
+outputformat="--output final"
+    if [ ! "$outputformat" == "--silent" ]; then
+        if [ ! "$outputformat" == "--output final" ]; then
+            echo
+        fi
+    fi
 	$runtests \
 		--colour \
-		--terse \
+		$outputformat \
 		--ignore-extra-analyses \
 		--section $section \
 	    --app $lookuptool \
 	    $fstoptions \
 	    $halftestoption \
-	    $testfile
+	    $testfile | tee -a testtotals.tmp.txt
+	exitv=$( echo ${PIPESTATUS[0]} )
+
 	# If the test failed, print instructions to rerun and get more details:
-	if [[ $? -gt 0 ]]; then
+	if [[ $exitv -gt 0 ]]; then
 	    let "Fail += 1"
-	    echo "To rerun with more details, please triple-click, copy and paste"
-	    echo "the following:"
+        printf "\033[1;31mFAIL\033[m\n"
+	    echo
+	    printf "To rerun with more details, please triple-click, copy and paste"
+	    echo " the following:"
 	    echo
 	    echo "pushd $(pwd); $runtests -c -i -v -S $section --app $lookuptool \
-	           $fstoptions $halftestoption $testfile; popd"
+$fstoptions $halftestoption $testfile; popd"
 	    echo
+	else
+	    if [ "$outputformat" == "--silent" \
+	      -o "$outputformat" == "--output final" ]; then
+	       printf "\033[0;32mPASS\033[m\n"
+	    fi
 	fi
 }
 
@@ -128,19 +145,19 @@ for f in $fsttype; do
 	# Check whether the actual fst's exist, run the tests if true, FAIL if not:
     if test "$halftest" == "ana" -a -f "$analyserfile.$f"; then
 		let "transducer_found += 1"
-		printf "$leadtext $testfileshort + $(basename $analyserfile.$f) - "
+		printf "$leadtext $(basename $analyserfile.$f) + $testfileshort - "
 		fstoptions="--morph $analyserfile.$f"
 		run_tests
 	elif test "$halftest" == "gen" -a -f "$generatorfile.$f"; then
 		let "transducer_found += 1"
-		printf "$leadtext $testfileshort + $(basename $generatorfile.$f) - "
+		printf "$leadtext $(basename $generatorfile.$f) + $testfileshort - "
 		fstoptions="--gen $generatorfile.$f"
 		run_tests
 	elif test "$halftest" == "full" \
 		-a -f "$analyserfile.$f"    \
 		-a -f "$generatorfile.$f"; then
 		let "transducer_found += 1"
-		printf "$leadtext $testfileshort + $(basename $analyserfile.$f) - "
+		printf "$leadtext $(basename $analyserfile.$f) + $testfileshort - "
 		fstoptions="--morph $analyserfile.$f --gen $generatorfile.$f"
 		run_tests
 	else
